# mkdocs.yml
site_name: "Cube"

site_url: https://naoki-okuda.github.io/shad/

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  #icon: heroicons:rocket-launch # use the shadcn svg if not defined
  #icon: assets/cube-solid.svg
  topbar_sections: true # NEW!
  katex_options: # optional
    macros: # example of macros
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: false 
  show_toc: true


use_directory_urls: false


markdown_extensions:
  - admonition #メモやアラートのための拡張
  - codehilite:
      guess_lang: true
      pygments_style: monokai
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences



extra_css:
  - extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js
  - js/katex_auto.js   # docs/js/katex_auto.js を後述の内容で作る


# file tree structure
nav:
  - Home: index.md
  - 非線形拡散: 01_non-lin-diff-analyticals.md
  - Jüttner分布 : 02juttner.md #相対論的な理想気体の分布関数
  - Maxwell-Vlasov系のスケール変換 : 03_scale_inv_VM.md
  - kinetics PROBLEM : LL_4_Collisions_in_Plasmas.md
  - biriv.f : 04_bitriv_f.md
  - F77_style : 05_F77_style.md
  - 変数 : 06_Variables.md







# extra_javascript:
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


